### ISSUE TITLE
Output file isn't created if a file is specified as the input source and a directory is specified as the output destination

### ISSUE THREAD

**Issue by 11rx4f** [eclipse/transformer#318]
##  Environment Details
* Transformer Version: org.eclipse.transformer.cli-0.3.0-20211026.182401-27-distribution.jar
* JDK version: 11
* OS: Windows Server 2019

## Problem Description
Output file isn't created if a file is specified as the input source and a directory is specified as the output destination.   
This problem occurs when a file other than the current directory is specified as the first argument.

## Steps to reproduce
```
>java -jar org.eclipse.transformer.cli-0.5.0-SNAPSHOT.jar C:\work\SimpleWS.war C:\work\result
...
[main] ERROR Transformer - Unexpected failure
java.nio.file.InvalidPathException: Illegal char <:> at index 16: C:\work\result\C:\work
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.io.File.toPath(File.java:2290)
        at aQute.lib.io.IO.mkdirs(IO.java:1071)
        at org.eclipse.transformer.action.impl.ZipActionImpl.applyFile(ZipActionImpl.java:147)
        at org.eclipse.transformer.action.impl.ZipActionImpl.apply(ZipActionImpl.java:116)
        at org.eclipse.transformer.Transformer.transform(Transformer.java:1232)
        at org.eclipse.transformer.Transformer.basicRun(Transformer.java:199)
        at org.eclipse.transformer.Transformer.run(Transformer.java:155)
        at org.eclipse.transformer.cli.TransformerCLI.run(TransformerCLI.java:387)
        at org.eclipse.transformer.cli.TransformerCLI.runWith(TransformerCLI.java:58)
        at org.eclipse.transformer.cli.JakartaTransformerCLI.main(JakartaTransformerCLI.java:24)
[main] INFO Transformer - Transformer Return Code [ 3 ] [ Transform Error ]
```

## Cause
https://github.com/eclipse/transformer/blob/a4002900aed92a4ec931cec37c778ec98dd816a4/org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java#L1025-L1034
inputName is a variable representing the value of the first argument itself entered in the java command.   
Therefore, if the first argument includes the path of directories, the output path becomes abnormal.   
If the first argument contains a directory path, the directory path should be excluded from the first argument value to determine the output path.

## Impact of Issue
Since specifying a file which exists outside the current directory is one of the most frequent operation, it is very inconvenient.

**Comment by bjhargrave** [comment]
Closing as a limitation of the design. There is no action implementation where the input and output are not the same type: file or directory.
