### ISSUE TITLE
Zip file conversion fails if it includes non-UTF-8 entry(such as MS932).

### ISSUE THREAD

**Issue by tsyamamoto** [eclipse/transformer#330]
##  Environment Details
* Transformer Version: org.eclipse.transformer.cli-0.5.0-20220610.152928-25-distribution.jar
* JDK version: 11
* OS: Windows Server 2019

## Problem Description
Zip file conversion fails if it includes non-UTF-8 entry(such as MS932).

Example)

```
[main] INFO Transformer - Action selected for input [ c:/dev/apps/japan.zip ]: Zip Action
[main] ERROR Transformer - Unexpected failure
java.lang.IllegalArgumentException: MALFORMED
        at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
        at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:300)
        at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
        at org.eclipse.transformer.action.impl.ZipActionImpl.applyZipStream(ZipActionImpl.java:288)
        at org.eclipse.transformer.action.impl.ZipActionImpl.applyStream(ZipActionImpl.java:219)
        at org.eclipse.transformer.action.impl.ZipActionImpl.applyFile(ZipActionImpl.java:196)
        at org.eclipse.transformer.action.impl.ZipActionImpl.apply(ZipActionImpl.java:132)
        at org.eclipse.transformer.Transformer.transform(Transformer.java:1242)
        at org.eclipse.transformer.Transformer.basicRun(Transformer.java:209)
        at org.eclipse.transformer.Transformer.run(Transformer.java:155)
        at org.eclipse.transformer.cli.TransformerCLI.run(TransformerCLI.java:387)
        at org.eclipse.transformer.cli.TransformerCLI.runWith(TransformerCLI.java:58)
        at org.eclipse.transformer.cli.JakartaTransformerCLI.main(JakartaTransformerCLI.java:24)
[main] INFO Transformer - Transformer Return Code [ 3 ] [ Transform Error ]
```

## Steps to reproduce
It is easily reproducible on Windows with a zip which contains a file whose file name encode is MS932.

## Cause
https://github.com/eclipse/transformer/blob/e6b73f6c7b2921a8bf62f801e16ce220cba1e64e/org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ZipActionImpl.java#L207-L209

Since no encoding is specified in the constructors of ZipInputStream and ZipOutputStream, UTF-8 is used to decode Zip entries.
Unlike jar files, zip files do not always have UTF-8 entries.

This can be fixed by designating non-UTF-8 encoding in the constructors of ZipInputStream and ZipOutputStream by introducing a new command option.

## Impact of Issue
The conversion to zip is not successful.

**Comment by bjhargrave** [comment]
@tsyamamoto, I am working on an alternate fix for this but I need to have a test case to confirm any fix. Can you please supply a zip with non-UTF-8 encoded entry names (such as `japan.zip` mentioned above) that can be included as test data for the tests?

**Comment by tsyamamoto** [comment]
This is a reproducible zip file.

[japan.zip](https://github.com/eclipse/transformer/files/8996964/japan.zip)

This zip file was created on Japanese Windows machine.
So it contains MS932 entry.
It also contains a war file which was created by jar command on Japanese Windows machine.
However, its entry is encoded by UTF-8.
Jar command seems to always encode entries in UTF -8.
