### ISSUE TITLE
Duplicate file property in jakarta-xml-master.properties causes java.io.FileNotFoundException

### ISSUE THREAD

**Issue by volosied** [eclipse/transformer#38]
I saw a few issues relating to XML transformations, but I didn't did see anything specific as this situation: 

My rules within _jakarta-xml-master.properties_:
```
com.ibm.ws.wsock.initializer.xml=jakarta-xml-servletContainerInitializer.properties
com.ibm.ws.webcontainer.xml=jakarta-xml-servletContainerInitializer.properties
```

Here jakarta-xml-servletContainerInitializer.properties is used twice. The file does exist, and the error is not seen when the second rule is comment out and only the first is used. 

Tested in Open Liberty jakartaee-transformer version **0.0.9**. 

Here's the output: 
```
[main] INFO Transformer - External [ Substitions matching [ web-fragment.xml ] ] URL [ file:/Users/siedlecki/libertyGit/open-liberty/dev/wlp-jakartaee-transform/rules/jakarta-xml-dd.properties ]
[main] INFO Transformer - Adjusted substition reference from [ jakarta-xml-servletContainerInitializer.properties  ] to [ /Users/siedlecki/libertyGit/open-liberty/dev/wlp-jakartaee-transform/rules/jakarta-xml-servletContainerInitializer.properties  ]
[main] INFO Transformer - External [ Substitions matching [ com.ibm.ws.webcontainer.xml ] ] URL [ file:/Users/siedlecki/libertyGit/open-liberty/dev/wlp-jakartaee-transform/rules/jakarta-xml-servletContainerInitializer.properties%20 ]
[main] ERROR Transformer - Exception loading rules:
java.io.FileNotFoundException: /Users/siedlecki/libertyGit/open-liberty/dev/wlp-jakartaee-transform/rules/jakarta-xml-servletContainerInitializer.properties  (No such file or directory)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at java.net.URL.openStream(URL.java:1057)
        at org.eclipse.transformer.util.FileUtils.loadProperties(FileUtils.java:214)
        at org.eclipse.transformer.Transformer.loadExternalProperties(Transformer.java:708)
        at org.eclipse.transformer.Transformer$TransformOptions.setRules(Transformer.java:934)
        at org.eclipse.transformer.Transformer.run(Transformer.java:1425)
        at com.ibm.ws.jakarta.transformer.JakartaTransformer.main(JakartaTransformer.java:36)
```

**Comment by volosied** [comment]
Don't believe this is a bug anymore. Closing.
