### ISSUE TITLE
java.lang.SecurityException: SHA-256 digest error for com/ibm/as400/access/TunnelProxyServer.class

### ISSUE THREAD

**Issue by ilapavuluri** [eclipse/transformer#538]
Hi All,

I am signing all my jars using jarsigner and using eclipse transformer for javax to jakarta conversion, after the transformation and when I deploy my application in wildfly I am getting java.lang.SecurityException even for signed jars, how to resolve it? do I need to sign the again after the eclipse transformation? please share your thoughts.

WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0003: Could not index class com/ibm/as400/access/TunnelProxyServer.class at ................................/lib/jt400.jar: java.lang.SecurityException: SHA-256 digest error for com/ibm/as400/access/TunnelProxyServer.class
	at java.base/sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:256)
	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:252)
	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:239)
	at java.base/java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:484)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:392)
	at io.smallrye.jandex//org.jboss.jandex.Indexer.verifyMagic(Indexer.java:2090)
	at io.smallrye.jandex//org.jboss.jandex.Indexer.indexWithSummary(Indexer.java:2485)
	at io.smallrye.jandex//org.jboss.jandex.Indexer.index(Indexer.java:2458)
	at org.jboss.as.server@23.0.1.Final//org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:82)
	at org.jboss.as.server@23.0.1.Final//org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:34)
	at org.jboss.as.server@23.0.1.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:172)
	at org.jboss.msc@1.5.2.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1617)
	at org.jboss.msc@1.5.2.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1580)
	at org.jboss.msc@1.5.2.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1438)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by bjhargrave** [comment]
See https://github.com/eclipse/transformer/issues/355#issuecomment-1213331959.

**Comment by bjhargrave** [comment]
> do I need to sign the again after the eclipse transformation?

Yes, you will need to sign the transformed jar.

**Comment by ilapavuluri** [comment]
@bjhargrave thank you for the response, please close the issue.
